### ISSUE TITLE
aleph error when shutting down a worker while a REPL client is connected

### ISSUE THREAD

**Issue by thheller** [thheller/shadow-devtools#4]
Called `.stop` on the aleph instance.

End up with this if there is still an open websocket connection. It is only a log message but still annoying .. and marked as SEVERE.

```
Apr 05, 2017 2:24:27 PM clojure.tools.logging$eval20437$fn__20441 invoke
SEVERE: error in deferred handler
java.util.concurrent.RejectedExecutionException: Executor is shutdown!
	at io.aleph.dirigiste.Executor.execute(Executor.java:300)
	at manifold.deferred.Deferred$fn__21268.invoke(deferred.clj:395)
	at manifold.deferred.Deferred.success(deferred.clj:395)
	at manifold.deferred$success_BANG_.invokeStatic(deferred.clj:243)
	at manifold.deferred$success_BANG_.invoke(deferred.clj:240)
	at manifold.stream.default.Stream$fn__22883.invoke(default.clj:81)
	at manifold.stream.default.Stream.close(default.clj:80)
	at manifold.stream.BufferedStream.close(stream.clj:863)
	at aleph.http.server$websocket_server_handler$reify__26442.channelInactive(server.clj:490)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at io.netty.handler.codec.MessageAggregator.channelInactive(MessageAggregator.java:406)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:360)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:325)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1329)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:908)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:744)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasksFrom(SingleThreadEventExecutor.java:379)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor.confirmShutdown(SingleThreadEventExecutor.java:678)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:452)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)

Apr 05, 2017 2:24:27 PM clojure.tools.logging$eval20437$fn__20441 invoke
SEVERE: error in deferred handler
java.util.concurrent.RejectedExecutionException: Executor is shutdown!
	at io.aleph.dirigiste.Executor.execute(Executor.java:300)
	at manifold.deferred.Deferred$fn__21268.invoke(deferred.clj:395)
	at manifold.deferred.Deferred.success(deferred.clj:395)
	at manifold.deferred$success_BANG_.invokeStatic(deferred.clj:243)
	at manifold.deferred$success_BANG_.invoke(deferred.clj:240)
	at manifold.stream.async.CoreAsyncSource$f__23348$fn__23349.invoke(async.clj:44)
	at clojure.core.async.impl.channels.ManyToManyChannel$fn__2554$fn__2555.invoke(channels.clj:95)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by thheller** [comment]
Fixed by using a shared executor for everything.
